### ISSUE TITLE
如何本地部署测试?

### ISSUE THREAD

**Issue by Lsun01** [thianda/phpweb#1]
请问如何部署测试,很少看到有关于网络的IP台账系统,想要部署本地测试一下,但是感觉跟普通的php源码有点不一样.

**Comment by yuxianda** [comment]
数据库部分需要配置并初始化录入。我没有给出来哦。不过并不影响本地搭建测试。

如果自己懂些技术的话搭建是很简单的。需要我提供帮助是有偿的哦。:dancers:请发邮件和我取得联系。
